#include "sparcli.h"
#include "args/args_internal.h"

#include <stdio.h>


/**
 * @file args_complete_bash.c
 * @brief Bash completion generation from the command tree.
 *
 * Mirrors the zsh generator's scope: root options, the first level of
 * subcommands and their options/positionals. Value options that declare
 * choices complete those choices after the option name.
 */


// Forward declarations indented to reflect call hierarchy
static void emit_opt_words(FILE *out, const ScArgsCmd *cmd, bool is_root);
static void emit_choice_cases(FILE *out, const ScArgsCmd *cmd,
                              const char *indent);


void sc_args_print_bash_completion(const ScArgs *args) {
    if (!args) { return; }
    FILE *out = sc_output_stream();
    const ScArgsCmd *root = &args->root;
    const char *prog = args->prog;
    bool has_subs = root->subcommand_count > 0;

    fprintf(out, "# bash completion for %s\n", prog);
    fprintf(out, "# Generated by sparcli (sc_args_print_bash_completion)\n");
    fprintf(out, "_%s() {\n", prog);
    fprintf(out, "    local cur prev cmd i\n");
    fprintf(out, "    cur=\"${COMP_WORDS[COMP_CWORD]}\"\n");
    fprintf(out, "    prev=\"${COMP_WORDS[COMP_CWORD-1]}\"\n\n");

    if (!has_subs) {
        emit_choice_cases(out, root, "    ");
        fprintf(out, "    if [[ \"$cur\" == -* ]]; then\n");
        fprintf(out, "        COMPREPLY=( $(compgen -W \"");
        emit_opt_words(out, root, true);
        fprintf(out, "\" -- \"$cur\") )\n");
        fprintf(out, "    else\n");
        fprintf(out, "        COMPREPLY=( $(compgen -f -- \"$cur\") )\n");
        fprintf(out, "    fi\n");
        fprintf(out, "}\n");
        fprintf(out, "complete -F _%s %s\n", prog, prog);
        return;
    }

    /* Detect the chosen subcommand: first non-option word after the prog. */
    fprintf(out, "    cmd=\"\"\n");
    fprintf(out, "    for ((i=1; i < COMP_CWORD; i++)); do\n");
    fprintf(out, "        case \"${COMP_WORDS[i]}\" in\n");
    fprintf(out, "            -*) ;;\n");
    fprintf(out, "            *) cmd=\"${COMP_WORDS[i]}\"; break ;;\n");
    fprintf(out, "        esac\n");
    fprintf(out, "    done\n\n");

    fprintf(out, "    case \"$cmd\" in\n");

    /* No subcommand yet: complete root options or the command list. */
    fprintf(out, "        \"\")\n");
    emit_choice_cases(out, root, "            ");
    fprintf(out, "            if [[ \"$cur\" == -* ]]; then\n");
    fprintf(out, "                COMPREPLY=( $(compgen -W \"");
    emit_opt_words(out, root, true);
    fprintf(out, "\" -- \"$cur\") )\n");
    fprintf(out, "            else\n");
    fprintf(out, "                COMPREPLY=( $(compgen -W \"");
    for (size_t i = 0; i < root->subcommand_count; i++) {
        fprintf(out, "%s%s", i ? " " : "", root->subcommands[i]->name);
    }
    fprintf(out, "\" -- \"$cur\") )\n");
    fprintf(out, "            fi\n");
    fprintf(out, "            ;;\n");

    /* Per-subcommand option completion. */
    for (size_t i = 0; i < root->subcommand_count; i++) {
        const ScArgsCmd *sub = root->subcommands[i];
        fprintf(out, "        %s)\n", sub->name);
        emit_choice_cases(out, sub, "            ");
        fprintf(out, "            COMPREPLY=( $(compgen -W \"");
        emit_opt_words(out, sub, false);
        fprintf(out, "\" -- \"$cur\") )\n");
        fprintf(out, "            ;;\n");
    }

    fprintf(out, "    esac\n");
    fprintf(out, "}\n");
    fprintf(out, "complete -F _%s %s\n", prog, prog);
}

/** Emits the space-separated option words (`-x --long … --help`). */
static void emit_opt_words(FILE *out, const ScArgsCmd *cmd, bool is_root) {
    for (size_t i = 0; i < cmd->option_count; i++) {
        const ArgOption *o = &cmd->options[i];
        if (o->short_name) { fprintf(out, "-%c ", o->short_name); }
        fprintf(out, "--%s ", o->long_name);
    }
    fprintf(out, "--help");
    if (is_root && cmd->owner && cmd->owner->version) {
        fprintf(out, " --version");
    }
}

/**
 * Emits `case "$prev"` branches that complete the declared choices of value
 * options (one branch per option, matching both spellings).
 */
static void emit_choice_cases(FILE *out, const ScArgsCmd *cmd,
                              const char *indent) {
    bool any = false;
    for (size_t i = 0; i < cmd->option_count; i++) {
        if (cmd->options[i].choice_count > 0) { any = true; break; }
    }
    if (!any) { return; }

    fprintf(out, "%scase \"$prev\" in\n", indent);
    for (size_t i = 0; i < cmd->option_count; i++) {
        const ArgOption *o = &cmd->options[i];
        if (o->choice_count == 0) { continue; }
        fprintf(out, "%s    ", indent);
        if (o->short_name) { fprintf(out, "-%c|", o->short_name); }
        fprintf(out, "--%s)\n", o->long_name);
        fprintf(out, "%s        COMPREPLY=( $(compgen -W \"", indent);
        for (size_t c = 0; c < o->choice_count; c++) {
            fprintf(out, "%s%s", c ? " " : "", o->choices[c]);
        }
        fprintf(out, "\" -- \"$cur\") ); return ;;\n");
    }
    fprintf(out, "%sesac\n", indent);
}
