#include "sparcli.h"
#include "args/args_internal.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>


/**
 * @file args_complete.c
 * @brief Zsh completion generation from the command tree.
 *
 * Emits a `#compdef` script covering the root options, the first level of
 * subcommands and their options/positionals (the layout the sparcli CLI
 * itself uses). Deeper nesting levels still parse correctly but are not
 * completed beyond their names.
 */


// Forward declarations indented to reflect call hierarchy
static void emit_option_specs(FILE *out, const ScArgsCmd *cmd, bool is_root);
    static void emit_one_option(FILE *out, const ArgOption *option);
        static void emit_escaped(FILE *out, const char *text);
static void emit_positional_specs(FILE *out, const ScArgsCmd *cmd);
static void emit_command_dispatch(FILE *out, const ScArgs *args);


void sc_args_print_zsh_completion(const ScArgs *args) {
    if (!args) { return; }
    FILE *out = sc_output_stream();
    const ScArgsCmd *root = &args->root;

    fprintf(out, "#compdef %s\n", args->prog);
    fprintf(out, "# Generated by sparcli (sc_args_print_zsh_completion)\n\n");
    fprintf(out, "_%s() {\n", args->prog);

    if (root->subcommand_count == 0) {
        // Flat tool: options + positionals in one _arguments call
        fprintf(out, "    _arguments \\\n");
        emit_option_specs(out, root, true);
        emit_positional_specs(out, root);
        fprintf(out, "        && return 0\n");
        fprintf(out, "}\n\n_%s \"$@\"\n", args->prog);
        return;
    }

    // Tool with subcommands: root options, then per-command dispatch
    fprintf(out, "    local curcontext=\"$curcontext\" state line\n");
    fprintf(out, "    typeset -A opt_args\n\n");
    fprintf(out, "    _arguments -C \\\n");
    emit_option_specs(out, root, true);
    fprintf(out, "        '1:command:->cmds' \\\n");
    fprintf(out, "        '*::arg:->args'\n\n");
    emit_command_dispatch(out, args);
    fprintf(out, "}\n\n_%s \"$@\"\n", args->prog);
}

/** Emits one `'--name[help]'`-style line per option (+ reserved ones). */
static void emit_option_specs(FILE *out, const ScArgsCmd *cmd, bool is_root) {
    for (size_t i = 0; i < cmd->option_count; i++) {
        emit_one_option(out, &cmd->options[i]);
    }

    fprintf(out, "        '--help[Show this help]' \\\n");
    if (is_root && cmd->owner && cmd->owner->version) {
        fprintf(out, "        '--version[Show the version]' \\\n");
    }
}

/** Emits the zsh spec of a single option. */
static void emit_one_option(FILE *out, const ArgOption *option) {
    fputs("        ", out);

    // Exclusion group + both spellings when a short alias exists
    if (option->short_name) {
        fprintf(
            out, "'(-%c --%s)'{-%c,--%s}'",
            option->short_name, option->long_name,
            option->short_name, option->long_name
        );
    } else {
        fprintf(out, "'--%s", option->long_name);
    }

    if (!option->is_flag) {
        fputs("=", out);
    }
    fputs("[", out);
    emit_escaped(out, option->help);
    fputs("]", out);

    if (!option->is_flag) {
        fputs(":", out);
        emit_escaped(
            out, option->metavar ? option->metavar : "value"
        );
        fputs(":", out);
        if (option->choice_count > 0) {
            fputs("(", out);
            for (size_t i = 0; i < option->choice_count; i++) {
                fprintf(out, "%s", i > 0 ? " " : "");
                emit_escaped(out, option->choices[i]);
            }
            fputs(")", out);
        }
    }
    fputs("' \\\n", out);
}

/** Writes `text` with zsh-special characters removed. */
static void emit_escaped(FILE *out, const char *text) {
    if (!text) { return; }
    for (const char *cursor = text; *cursor; cursor++) {
        // Brackets/quotes/colons would break the completion spec syntax
        bool is_special = *cursor == '[' || *cursor == ']' || *cursor == '\''
            || *cursor == ':' || *cursor == '`';
        if (!is_special) {
            fputc(*cursor, out);
        }
    }
}

/** Emits the positional specs (`'*:FILE:_files'` style). */
static void emit_positional_specs(FILE *out, const ScArgsCmd *cmd) {
    for (size_t i = 0; i < cmd->positional_count; i++) {
        const ArgPositional *positional = &cmd->positionals[i];
        if (positional->variadic) {
            fputs("        '*:", out);
        } else {
            fprintf(out, "        '%zu:", i + 1);
        }
        emit_escaped(out, positional->name);
        fputs(":_files' \\\n", out);
    }
}

/** Emits the `case $state` dispatch with one block per subcommand. */
static void emit_command_dispatch(FILE *out, const ScArgs *args) {
    const ScArgsCmd *root = &args->root;

    fprintf(out, "    case $state in\n");
    fprintf(out, "        cmds)\n");
    fprintf(out, "            local -a commands=(\n");
    for (size_t i = 0; i < root->subcommand_count; i++) {
        const ScArgsCmd *subcommand = root->subcommands[i];
        fputs("                '", out);
        emit_escaped(out, subcommand->name);
        fputs(":", out);
        emit_escaped(out, subcommand->about);
        fputs("'\n", out);
    }
    fprintf(out, "            )\n");
    fprintf(out, "            _describe -t commands 'command' commands\n");
    fprintf(out, "            ;;\n");
    fprintf(out, "        args)\n");
    fprintf(out, "            case $line[1] in\n");

    for (size_t i = 0; i < root->subcommand_count; i++) {
        const ScArgsCmd *subcommand = root->subcommands[i];
        fputs("                ", out);
        emit_escaped(out, subcommand->name);
        fputs(")\n", out);
        fprintf(out, "                    _arguments \\\n");
        emit_option_specs(out, subcommand, false);
        emit_positional_specs(out, subcommand);
        fprintf(out, "                        && return 0\n");
        fprintf(out, "                    ;;\n");
    }

    fprintf(out, "            esac\n");
    fprintf(out, "            ;;\n");
    fprintf(out, "    esac\n");
}
