#include "sparcli.h"
#include "args/args_internal.h"

#include <stdio.h>


/**
 * @file args_complete_fish.c
 * @brief Fish completion generation from the command tree.
 *
 * Emits `complete -c <prog>` lines: subcommands (gated by
 * `__fish_use_subcommand`), root options, and each subcommand's options
 * (gated by `__fish_seen_subcommand_from <name>`). Value options are marked
 * `-r` and complete their choices when declared.
 */


// Forward declarations indented to reflect call hierarchy
static void emit_fish_escaped(FILE *out, const char *text);
static void emit_options(
    FILE *out, const char *prog, const ScArgsCmd *cmd,
    const char *condition, bool is_root
);


void sc_args_print_fish_completion(const ScArgs *args) {
    if (!args) { return; }
    FILE *out = sc_output_stream();
    const ScArgsCmd *root = &args->root;
    const char *prog = args->prog;
    bool has_subs = root->subcommand_count > 0;

    fprintf(out, "# fish completion for %s\n", prog);
    fprintf(out, "# Generated by sparcli (sc_args_print_fish_completion)\n");

    if (!has_subs) {
        emit_options(out, prog, root, NULL, true);
        return;
    }

    /* Subcommands (only suggested before one is chosen). */
    for (size_t i = 0; i < root->subcommand_count; i++) {
        const ScArgsCmd *sub = root->subcommands[i];
        fprintf(out, "complete -c %s -f -n __fish_use_subcommand -a %s -d \"",
                prog, sub->name);
        emit_fish_escaped(out, sub->about ? sub->about : "");
        fprintf(out, "\"\n");
    }

    /* Root options, valid before a subcommand is chosen. */
    emit_options(out, prog, root, "__fish_use_subcommand", true);

    /* Per-subcommand options. */
    for (size_t i = 0; i < root->subcommand_count; i++) {
        const ScArgsCmd *sub = root->subcommands[i];
        char cond[128];
        snprintf(cond, sizeof cond, "__fish_seen_subcommand_from %s",
                 sub->name);
        emit_options(out, prog, sub, cond, false);
    }
}

/** Emits one `complete` line per option of `cmd`. */
static void emit_options(
    FILE *out, const char *prog, const ScArgsCmd *cmd,
    const char *condition, bool is_root
) {
    for (size_t i = 0; i < cmd->option_count; i++) {
        const ArgOption *o = &cmd->options[i];
        fprintf(out, "complete -c %s", prog);
        if (condition) { fprintf(out, " -n \"%s\"", condition); }
        if (o->short_name) { fprintf(out, " -s %c", o->short_name); }
        fprintf(out, " -l %s", o->long_name);
        if (!o->is_flag) {
            fprintf(out, " -r");
            if (o->choice_count > 0) {
                fprintf(out, " -a \"");
                for (size_t c = 0; c < o->choice_count; c++) {
                    fprintf(out, "%s%s", c ? " " : "", o->choices[c]);
                }
                fprintf(out, "\"");
            }
        }
        if (o->help && o->help[0]) {
            fprintf(out, " -d \"");
            emit_fish_escaped(out, o->help);
            fprintf(out, "\"");
        }
        fprintf(out, "\n");
    }

    /* Reserved options. */
    fprintf(out, "complete -c %s", prog);
    if (condition) { fprintf(out, " -n \"%s\"", condition); }
    fprintf(out, " -l help -d \"Show this help\"\n");
    if (is_root && cmd->owner && cmd->owner->version) {
        fprintf(out, "complete -c %s", prog);
        if (condition) { fprintf(out, " -n \"%s\"", condition); }
        fprintf(out, " -l version -d \"Show the version\"\n");
    }
}

/** Writes `text` with `"` and `\` backslash-escaped for a fish string. */
static void emit_fish_escaped(FILE *out, const char *text) {
    if (!text) { return; }
    for (const char *p = text; *p; p++) {
        if (*p == '"' || *p == '\\') { fputc('\\', out); }
        fputc(*p, out);
    }
}
